### ISSUE TITLE
Invalid Quote when Price is > 999

### ISSUE THREAD

**Issue by derekrowley** [davidguttman/y-options#1]
In index.js when parsing a quote in parseQuote if the price of the stock has a comma in the value then parseFloat returns 1 rather than the actual price of the stock.  Suggestion is to remove commas from the price before calling parseFloat.

**Comment by davidguttman** [comment]
Good catch, thanks for the issue!

**Comment by derekrowley** [comment]
Wow, thanks for fixing it so fast :).  Love the module btw.
